version: "3.1"
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  postgres-data:
  redis-data:
